spring:
  application:
    name: parking-backend
  datasource:
    url: jdbc:mysql://localhost:3306/parking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    open-in-view: false
    open-in-view: true

server:
  port: 8080

jwt:
  secret: swp391-parking-dev-secret-key-must-be-at-least-256-bits-long-string
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs