Table parking_building {
building_id int [pk, increment]
name varchar(100) [not null]
address varchar(255) [not null]
operating_hours varchar(50)
total_floors int
status varchar(20) [not null] // ACTIVE, INACTIVE, MAINTENANCE
created_at datetime
updated_at datetime
}

Table floor {
floor_id int [pk, increment]
building_id int [not null, ref: > parking_building.building_id]
floor_number int [not null]
floor_name varchar(50)
status varchar(20) [not null] // ACTIVE, INACTIVE, MAINTENANCE
created_at datetime
updated_at datetime
}

Table vehicle_type {
vehicle_type_id int [pk, increment]
name varchar(50) [not null, unique] // MOTORBIKE, CAR, ELECTRIC_CAR
created_at datetime
updated_at datetime
}

Table zone {
zone_id int [pk, increment]
floor_id int [not null, ref: > floor.floor_id]
vehicle_type_id int [not null, ref: > vehicle_type.vehicle_type_id]
zone_name varchar(50) [not null]
status varchar(20) [not null] // ACTIVE, INACTIVE, MAINTENANCE
created_at datetime
updated_at datetime
}

Table parking_slot {
slot_id int [pk, increment]
zone_id int [not null, ref: > zone.zone_id]
slot_code varchar(20) [not null, unique]
priority int
distance_to_gate int
status varchar(20) [not null] // AVAILABLE, RESERVED, OCCUPIED, MAINTENANCE
created_at datetime
updated_at datetime
}

Table user {
user_id int [pk, increment]
username varchar(50) [not null, unique]
full_name varchar(100) [not null]
email varchar(100) [not null, unique]
phone varchar(20)
password_hash varchar(255) [not null]
status varchar(20) [not null] // ACTIVE, INACTIVE, LOCKED
created_at datetime
updated_at datetime
}

Table role {
role_id int [pk, increment]
role_name varchar(50) [not null, unique] // ADMIN, MANAGER, STAFF, DRIVER
}

Table user_role {
user_id int [not null, ref: > user.user_id]
role_id int [not null, ref: > role.role_id]

indexes {
(user_id, role_id) [pk]
}
}

Table vehicle {
vehicle_id int [pk, increment]
owner_user_id int [not null, ref: > user.user_id]
vehicle_type_id int [not null, ref: > vehicle_type.vehicle_type_id]
license_plate varchar(20) [not null, unique]
created_at datetime
updated_at datetime
}

Table booking {
booking_id int [pk, increment]
user_id int [not null, ref: > user.user_id]
vehicle_id int [ref: > vehicle.vehicle_id]
slot_id int [not null, ref: > parking_slot.slot_id]
booking_start_time datetime
booking_end_time datetime
reserved_at datetime
expired_at datetime
status varchar(30) [not null] // PENDING_PAYMENT, CONFIRMED, CHECKED_IN, EXPIRED, CANCELLED, COMPLETED
created_at datetime
updated_at datetime
}

Table parking_session {
session_id int [pk, increment]
booking_id int [ref: > booking.booking_id]
slot_id int [not null, ref: > parking_slot.slot_id]
user_id int [not null, ref: > user.user_id]
vehicle_id int [not null, ref: > vehicle.vehicle_id]
entry_gate_id int [ref: > gate.gate_id]
exit_gate_id int [ref: > gate.gate_id]
entry_time datetime
exit_time datetime
entry_mode varchar(20) [not null] // BOOKING, WALK_IN_AUTO, WALK_IN_MANUAL
status varchar(30) [not null] // ACTIVE, WAITING_PAYMENT, COMPLETED, EXCEPTION
created_at datetime
updated_at datetime
}

Table ticket {
ticket_id int [pk, increment]
session_id int [not null, ref: > parking_session.session_id]
ticket_code varchar(50) [not null, unique]
ticket_type varchar(20) [not null] // BOOKING, WALK_IN
issued_at datetime [not null]
status varchar(20) [not null] // ACTIVE, LOST, CLOSED
created_at datetime
updated_at datetime
}

Table pricing_policy {
policy_id int [pk, increment]
vehicle_type_id int [not null, ref: > vehicle_type.vehicle_type_id]
time_type varchar(20) [not null] // HOURLY, DAILY, OVERNIGHT
day_type varchar(20) [not null] // WEEKDAY, WEEKEND, HOLIDAY
start_hour int
end_hour int
price_per_hour decimal(10,2) [not null]
is_active boolean [not null]
created_at datetime
updated_at datetime
}

Table payment {
payment_id int [pk, increment]
session_id int [not null, ref: > parking_session.session_id]
policy_id int [ref: > pricing_policy.policy_id]
applied_rate decimal(10,2)
base_fee decimal(12,2)
overtime_fee decimal(12,2)
penalty_fee decimal(12,2)
discount decimal(12,2)
total_amount decimal(12,2) [not null]
transaction_ref varchar(100) [unique]
payment_method varchar(20) [not null] // CASH, MOCK, VNPAY
payment_status varchar(20) [not null] // PENDING, PAID, FAILED, REFUNDED, CANCELLED
paid_at datetime
created_at datetime
updated_at datetime
}

Table gate {
gate_id int [pk, increment]
building_id int [not null, ref: > parking_building.building_id]
gate_code varchar(50) [not null, unique]
gate_type varchar(20) [not null] // ENTRY, EXIT, BOTH
created_at datetime
updated_at datetime
}

Table gate_log {
gate_log_id int [pk, increment]
gate_id int [not null, ref: > gate.gate_id]
session_id int [ref: > parking_session.session_id]
staff_user_id int [ref: > user.user_id]
license_plate varchar(20)
event_type varchar(30) [not null] // ENTRY, EXIT
result_status varchar(20) [not null] // SUCCESS, FAILED, MANUAL_CHECK
event_time datetime [not null]
created_at datetime
updated_at datetime
}

Table ocr_scan {
scan_id int [pk, increment]
session_id int [ref: > parking_session.session_id]
gate_id int [ref: > gate.gate_id]

image_path varchar(500)

detected_plate varchar(20)
plate_confidence_score float

corrected_plate varchar(20)

staff_vehicle_type_id int [ref: > vehicle_type.vehicle_type_id]

is_corrected boolean [not null]
corrected_by int [ref: > user.user_id]
corrected_at datetime
correction_reason varchar(255)

trigger_type varchar(20) [not null] // ENTRY, EXIT

process_status varchar(30) [not null]
// AUTO_APPROVED, MANUAL_REVIEW, STAFF_APPROVED, CORRECTED_AFTER_APPROVAL, FAILED

scanned_at datetime
}


Table request {
request_id int [pk, increment]
user_id int [not null, ref: > user.user_id]
assigned_staff_id int [ref: > user.user_id]
request_type varchar(30) [not null] // LOST_CARD, WRONG_FEE, CANNOT_FIND_CAR, OTHER
subject varchar(200)
description text
status varchar(20) [not null] // PENDING, PROCESSING, RESOLVED, REJECTED, CLOSED
resolved_at datetime
created_at datetime
updated_at datetime
}

Table exception_case {
exception_id int [pk, increment]
session_id int [ref: > parking_session.session_id]
request_id int [ref: > request.request_id]
exception_type varchar(30) [not null]
description varchar(500)
status varchar(20) [not null] // OPEN, PROCESSING, RESOLVED, CLOSED
resolved_by int [ref: > user.user_id]
resolved_at datetime
created_at datetime
updated_at datetime
}

Table notification {
notification_id int [pk, increment]
user_id int [not null, ref: > user.user_id]
title varchar(200) [not null]
body text
type varchar(50)
entity_type varchar(30)
entity_id int
is_read boolean [not null]
created_at datetime
}

Table activity_log {
log_id bigint [pk, increment]
user_id int [ref: > user.user_id]
action_type varchar(50)
action varchar(200) [not null]
ip_address varchar(50)
created_at datetime
}

Table shift {
shift_id int [pk, increment]
shift_name varchar(50) [not null]
start_time time [not null]
end_time time [not null]
status varchar(20) [not null] // ACTIVE, INACTIVE
}

Table staff_shift {
staff_shift_id int [pk, increment]
staff_user_id int [not null, ref: > user.user_id]
shift_id int [not null, ref: > shift.shift_id]
working_date date [not null]
}

Table system_config {
config_id bigint [pk, increment]
config_key varchar(100) [not null, unique]
config_value varchar(255)
description varchar(255)
updated_by int [ref: > user.user_id]
updated_at datetime
}

Table password_reset_token {
token_id int [pk, increment]
user_id int [not null, ref: > user.user_id]
token varchar(255) [not null, unique]
expires_at datetime [not null]
used boolean [not null]
created_at datetime
}
